name: Node.js CI

on:
  pull_request:
    branches: ['dev']
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install all necessary dependencies
        run: npm ci
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Run Karma unit tests
        run: npm test -- --no-watch --no-progress

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install all necessary dependencies
        run: npm ci
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Clone games library and install dependencies
        run: |
          git clone https://github.com/KN-GEST-ongit/rag-2-games.git
          cd rag-2-games
          npm i
          npm run games:build
          npm run games:link
      - name: Install Cypress
        run: npm install cypress --save-dev
      - name: Install library
        run: npm run games:import
      - name: Run Cypress E2E tests
        run: npx ng e2e --no-watch --headless
